### ISSUE TITLE
Getting error and no idea where to get the required pdfToHtml.exe file

### ISSUE THREAD

**Issue by infact** [kerajel/PdfToHtmlNet#1]
Getting error and no idea where to get the required pdfToHtmlNet.exe file

nuget package is installed, but still getting this error.
Error	CS1566	Error reading resource 'PdfToHtmlNet.Repository.PdfToHtmlNet.exe' -- 'Could not find a part of the path '..\PdfToHtmlNet.Python\Executable\PdfToHtmlNet.exe'.'	PdfToHtmlNet.Repository (netstandard2.1)

**Comment by kerajel** [comment]
Hi! Try to specify executable's directory directly:

PdfToHtmlNet.Converter c = new PdfToHtmlNet.Converter();
c.ExecutableDirectory = "directory path";

pdfToHtmlNet.exe will deploy itself on initialization

Make sure you have necessary rights for write operations for this directory

**Comment by infact** [comment]
@kerajel  for that to happen, either I need the pdfToHtmlNet.exe on my system. I don't have it , in your project, I can see the exe is showing as unavailable. It looks like you included the source code for the  same in PdfToHtmlNet.Python\Script. I tried to run the python file from my windows system to see if I can generate the exe, but getting error  
![image](https://user-images.githubusercontent.com/9020432/129407524-9e686ce4-5674-42aa-8de5-5f1b2160c126.png)

**Comment by kerajel** [comment]
This executable is an embedded resource of library's .nupkg and is stored as byte array. Method DeployExecutable makes sure it is deployed on your machine when calling ConvertToFile. Are you sure you use this method?

Executable is git ignored as well, that's why you don't see it in cloned project. If you really want a separate .exe file (you don't, really) you can run PdfToHtmlPy_Builder.py (make sure you have pyinstaller installed)

**Comment by infact** [comment]
@kerajel  Yes ,that worked. Thank you for your quick responses. @kerajel
